runtime: python39
service: adk-mobile-service

env_variables:
  PROJECT_ID: "twothreeatefi"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto
  secure: always

entrypoint: gunicorn -b :$PORT main:app --workers 2 --threads 8 --timeout 120